"""Optional non-authoritative summary layer based on deterministic trace metadata."""

from __future__ import annotations

import json
import os
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class LLMSummaryResult:
    requested: bool
    summary_written: bool
    external_llm_used: bool
    provider: str | None
    output_path: str | None
    skipped_reason: str | None
    warnings: list[str]


def build_llm_summary_input(trace_data: dict) -> dict:
    key_checks = trace_data.get("key_checks", {})
    record_comparison = trace_data.get("record_comparison", {})
    value_comparison = trace_data.get("value_comparison", {})
    output_files = trace_data.get("output_files", {})
    return {
        "mode": trace_data.get("mode"),
        "key_mode": trace_data.get("key_mode"),
        "source_path": trace_data.get("source_path"),
        "target_path": trace_data.get("target_path"),
        "source_row_count": trace_data.get("source_row_count"),
        "target_row_count": trace_data.get("target_row_count"),
        "matched_key_count": record_comparison.get("matched_key_count"),
        "missing_in_target_count": record_comparison.get("missing_in_target_count"),
        "unexpected_in_target_count": record_comparison.get("unexpected_in_target_count"),
        "duplicate_key_row_count_source": key_checks.get("duplicate_key_row_count_source"),
        "duplicate_key_row_count_target": key_checks.get("duplicate_key_row_count_target"),
        "null_key_count_source": key_checks.get("null_key_count_source"),
        "null_key_count_target": key_checks.get("null_key_count_target"),
        "value_comparison_enabled": value_comparison.get("enabled"),
        "value_mismatch_count": value_comparison.get("mismatched_value_count"),
        "mismatches_by_field": value_comparison.get("mismatched_field_counts", {}),
        "exceptions_written": output_files.get("exceptions_written", []),
        "warnings": trace_data.get("warnings", []),
        "blocking_errors": trace_data.get("blocking_errors", []),
    }


def build_summary_prompt(summary_input: dict) -> str:
    facts = json.dumps(summary_input, indent=2, sort_keys=True)
    return (
        "You are writing a readability-only executive summary for a deterministic reconciliation run.\n"
        "Deterministic outputs are authoritative; your summary is non-authoritative.\n"
        "Do not invent findings. Do not change counts. Use only the provided structured facts.\n"
        "Do not infer row-level details. Mention limitations and direct readers to evidence files.\n"
        "Produce concise markdown with: Executive summary, Key findings, Evidence files to inspect, Limitations.\n\n"
        "Structured facts:\n"
        f"{facts}\n"
    )


def _write_summary_markdown(output_dir: Path, summary_input: dict, generated_by_external_llm: bool) -> str:
    output_path = output_dir / "llm_summary.md"
    mode_line = (
        "Generated by optional LLM polish from deterministic trace metadata."
        if generated_by_external_llm
        else "Generated without an external LLM from deterministic trace metadata."
    )
    lines = [
        "# Optional LLM Summary",
        "",
        "**This is a non-authoritative readability summary. The deterministic trace, report, and exception CSVs remain the source of truth.**",
        "",
        mode_line,
        "",
        "## Executive summary",
        (
            f"Compared {summary_input['source_row_count']} source rows and {summary_input['target_row_count']} target rows "
            f"using key mode `{summary_input['key_mode']}`."
        ),
        "",
        "## Key findings",
        f"- Matched keys: {summary_input['matched_key_count']}",
        f"- Missing from target: {summary_input['missing_in_target_count']}",
        f"- Unexpected in target: {summary_input['unexpected_in_target_count']}",
        f"- Value comparison enabled: {summary_input['value_comparison_enabled']}",
        f"- Value mismatches: {summary_input['value_mismatch_count']}",
        "",
        "### Mismatches by field",
    ]
    mismatch_items = summary_input.get("mismatches_by_field", {})
    lines.extend([f"- {name}: {count}" for name, count in mismatch_items.items()] or ["- (none)"])
    lines.extend([
        "",
        "## Evidence files to inspect",
        "- reconciliation_trace.json",
        "- reconciliation_report.md",
    ])
    lines.extend([f"- {name}" for name in summary_input.get("exceptions_written", [])])
    lines.extend([
        "",
        "## Limitations",
        "- This summary is readability-only and not evidence.",
        "- Review deterministic artifacts for authoritative details.",
    ])
    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return str(output_path)


def generate_llm_summary(trace_path: str, output_dir: str, provider: str | None = None) -> LLMSummaryResult:
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)
    trace_data = json.loads(Path(trace_path).read_text(encoding="utf-8"))
    summary_input = build_llm_summary_input(trace_data)
    _ = build_summary_prompt(summary_input)

    selected_provider = provider or ("openai" if os.getenv("OPENAI_API_KEY") else None)
    warnings: list[str] = []

    if selected_provider is None:
        reason = "no provider/API key configured"
        warnings.append("External LLM not used because no provider/API key was configured.")
        output_path = _write_summary_markdown(out, summary_input, generated_by_external_llm=False)
        return LLMSummaryResult(True, True, False, "deterministic_fallback", output_path, None, warnings)

    if selected_provider != "openai":
        reason = f"provider '{selected_provider}' is not supported"
        output_path = _write_summary_markdown(out, summary_input, generated_by_external_llm=False)
        warnings.append(f"External LLM not used because {reason}.")
        return LLMSummaryResult(True, True, False, "deterministic_fallback", output_path, None, warnings)

    if not os.getenv("OPENAI_API_KEY"):
        reason = "OPENAI_API_KEY is not set"
        output_path = _write_summary_markdown(out, summary_input, generated_by_external_llm=False)
        warnings.append("External LLM not used because OPENAI_API_KEY is not set.")
        return LLMSummaryResult(True, True, False, "deterministic_fallback", output_path, None, warnings)

    warnings.append("openai provider integration is not installed; used deterministic fallback summary")
    output_path = _write_summary_markdown(out, summary_input, generated_by_external_llm=False)
    return LLMSummaryResult(True, True, False, "deterministic_fallback", output_path, None, warnings)
